### ISSUE TITLE
Max Date work not smooth

### ISSUE THREAD

**Issue by kokorolee** [dolymood/date-time-picker#10]
Max date css not work when you make `max` in this month
In this picture:
Mindate: 2019-02-14
Maxdate: 2019-02-15
![image](https://user-images.githubusercontent.com/35665527/52761645-c0ae4080-3046-11e9-983c-078a7adf4f13.png)

But when make `max` in other month it work ok.
Mindate: 2019-02-28
Maxdate: 2019-03-01
![image](https://user-images.githubusercontent.com/35665527/52761696-feab6480-3046-11e9-97bc-c159a06a37e9.png)
![image](https://user-images.githubusercontent.com/35665527/52761702-0965f980-3047-11e9-8a51-a5e8aac74ede.png)

**Comment by dolymood** [comment]
0.5.3 fixed this issue.
