### ISSUE TITLE
主题样式无法覆盖，求思路

### ISSUE THREAD

**Issue by evanoxu** [dolymood/date-time-picker#3]
你好，我在vue项目里引入里你的组件之后，尝试着修改主题样式，但是改不了。
每次触发的时候，组件自带样式默认加载在head最后面，导致我前面修改的样式优先级低于组件的。

请问有啥好的思路能解决吗？

**Comment by dolymood** [comment]
你是通过 require（import）的形式依赖的 css 是吧  可能是这个原因 https://github.com/webpack/webpack/issues/215

或许你可以把依赖前置下 或者修改下 require顺序

**Comment by dolymood** [comment]
样式覆盖可参考 https://github.com/dolymood/date-time-picker/blob/master/src/css/dark.css 或
 https://github.com/dolymood/date-time-picker/blob/master/src/css/light.css
