### ISSUE TITLE
Not support mouse events

### ISSUE THREAD

**Issue by jaypatel512** [dolymood/date-time-picker#5]
Hey there,

Loved your UI. Tried to implement using your example. In my case, when I click on anything nothing happens. 

When I click on "Show Date", your UI opens, but then, I cannot click on anything. Even OK and CANCEL does not work.

**Comment by dolymood** [comment]
Thanks.
Is it on mobile devices? Only support touch events for now.

**Comment by KtorZ** [comment]
Hi, great work!
Any plan to support click events in the near future?

**Comment by dolymood** [comment]
Hey, @jaypatel512  @KtorZ   0.5.0 supported mouse events, you can try it. 😄
